version: '3'

services:
  lambda:
    # build: ./lambda
    # command: python persistForecast.py
    # environment:
    image: persistforecast
    env_file: ".env"
    ports:
      - "9000:8080"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cel
    ports:
      - "5432:5432"