version: '3'

services:
  persist:
    build:
      dockerfile: ./DockerfilePersist
    env_file: ".env"
    ports:
      - "9000:8080"
      # - "db:5432"
  
  # serve:
  #   build:
  #     dockerfile:  ./DockerfileService
  #   env_file: ".env"
  #   ports:
  #     - "9001:8080"
  #     # - "5432:5432"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cel
    ports:
      - "5432:5432"